[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration = { workspace = true }
entity = { path = "../entity" }
tokio = { workspace = true }

[dependencies.sea-orm]
workspace = true
